### ISSUE TITLE
[Application] : alexprimak

### ISSUE THREAD

**Issue by alexprimak24** [fuel-champions/veteran-applications#2]
### Proof of your code

https://github.com/alexprimak58/data-structures-in-sway

### Fuel projects you have worked on

https://github.com/alexprimak58/data-structures-in-sway

### Activity on the Fuel forum

https://forum.fuel.network/u/alexprimak/summary

### Proof of content creation

All my Publications in Mirror: https://mirror.xyz/0x65B48f58f49Ab335169844F9F75f3Cb3fE848483

My Special Section about Fuel in My Youtube channel: https://www.youtube.com/playlist?list=PLISxc1hz2qeEv4vvBXMglEgOCU63zKlqm

+X Threads,you can find some in Fuel Discord in Random Section,example: https://twitter.com/alexprimak24/status/1735652910384456109?s=20

### Links to your social media profiles

Twitter: https://twitter.com/alexprimak24

Youtube: https://www.youtube.com/channel/UCMLabRYeBP7EAr4P435SgoQ

Mirror: https://mirror.xyz/0x65B48f58f49Ab335169844F9F75f3Cb3fE848483

### Current Champions member

None

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
HI @alexprimak58,

We've reviewed your application and delighted to share that you have been approved as a **Pioneer** in the Fuel Developer Champions program! 🎉

We are so excited to welcome you into the community of Champions! 🏆

Ben
