### ISSUE TITLE
[Application] : Brandon (bleedo_eth)

### ISSUE THREAD

**Issue by brandonsurh** [fuel-champions/veteran-applications#3]
## [FuelLabs/sway](https://github.com/FuelLabs/sway)
- [Added assert_ne(x, y) function #5426](https://github.com/FuelLabs/sway/pull/5426)
- [Added tests for the sqrt() method in math.sw #5423](https://github.com/FuelLabs/sway/pull/5423)
- [Implements the Hash trait for EvmAddress #5422](https://github.com/FuelLabs/sway/pull/5422)
- [Implements the Eq trait for Option #5302](https://github.com/FuelLabs/sway/pull/5302)
- [Added keccak256 tests for Hasher #5172](https://github.com/FuelLabs/sway/pull/5172)
- [SwayFmt: remove {} around single imports #5109](https://github.com/FuelLabs/sway/pull/5109)

## [FuelLabs/sway-libs](https://github.com/FuelLabs/sway-libs)
- [Queue Documentation and Specification #168](https://github.com/FuelLabs/sway-libs/pull/168)

## [FuelLabs/sway-farm](https://github.com/FuelLabs/sway-farm)
- [Add button to github for contributors #22](https://github.com/FuelLabs/sway-farm/pull/22)

## [FuelLabs/sway-applications](https://github.com/FuelLabs/sway-applications)
- [Escrow paths mod #300](https://github.com/FuelLabs/sway-applications/pull/300)
- [Fundraiser paths mod #299](https://github.com/FuelLabs/sway-applications/pull/299)
- [Forc test change #297](https://github.com/FuelLabs/sway-applications/pull/297)
- [Removed std prelude imports #295](https://github.com/FuelLabs/sway-applications/pull/295)

### Repos
- [FuelLabs/sway](https://github.com/FuelLabs/sway)

### Activity on the Fuel forum

https://forum.fuel.network/u/bleedo/summary

### Proof of content creation

https://medium.com/@bleedo_eth/a-look-at-predicates-in-sway-952f99cabbd4

_Note: older than three months_

### Links to your social media profiles

https://twitter.com/bleedo_eth
https://www.linkedin.com/in/brandon-surh/

### Current Champions member

No, I'm not a Fuel Developer Champion yet

### Fuel Ambassador Program

Yes, I'm a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
Hi @brandonsurh,

We've reviewed your application and delighted to share that you have been approved as an **Explorer** in the Fuel Developer Champions program! 🎉 

We are so excited to welcome you into the community of Champions! 🏆 

Ben

**Comment by brandonsurh** [comment]
Awesome! It's great to be on the team 👍
