### ISSUE TITLE
[Application] : Ankit AKA chappie

### ISSUE THREAD

**Issue by chappie1998** [fuel-champions/veteran-applications#4]
### Proof of your code

https://github.com/Vistara-Labs/vimana/pull/11

### Fuel projects you have worked on

fuelart.io
unic.io

### Activity on the Fuel forum

https://forum.fuel.network/u/chappie1998/summary

### Links to your social media profiles

https://twitter.com/chappie_1998
https://www.linkedin.com/in/ankit-kumar-saini-060527173/

### Current Champions member

Yes, I'm a Pioneer and applying to level up to Explorer

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
Hi @chappie1998,

We've reviewed your application and delighted to share that you have been approved as an **Explorer** in the Fuel Developer Champions program! 🎉

We are so excited to welcome you into the community of Champions! 🏆

Ben
