### ISSUE TITLE
[Application] : Haardik H

### ISSUE THREAD

**Issue by haardikk21** [fuel-champions/veteran-applications#5]
### Proof of your code

- https://learnweb3.io/courses/full-stack-fuel-course
- https://github.com/LearnWeb3DAO/fuel-painter
- WIP Social Recovery Wallet shared in Fuel Buidlers
- WIP Limit Orders shared in Fuel Builders

Non-Fuel stuff:
- Variety of repos in https://github.com/haardikk21 and https://github.com/LearnWeb3DAO - 99.9% crypto stuff

### Fuel projects you have worked on

- https://learnweb3.io/courses/full-stack-fuel-course
- https://github.com/LearnWeb3DAO/fuel-painter
- WIP Social Recovery Wallet shared in Fuel Buidlers
- WIP Limit Orders shared in Fuel Builders

### Activity on the Fuel forum

N/A

### Proof of content creation

- https://learnweb3.io/courses/full-stack-fuel-course

### Links to your social media profiles

https://twitter.com/haardikkk
https://warpcast.com/haardikkk

### Current Champions member

None

### Fuel Ambassador Program

None

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
Hi @haardikk21 Welcome to the Fuel Developer Champions program! We are so excited to have you here.
