### ISSUE TITLE
[Application] : Yusong

### ISSUE THREAD

**Issue by peter209393** [fuel-champions/veteran-applications#7]
### Proof of your code

https://github.com/FuelLabs/fuel-core/pull/1293
https://github.com/FuelLabs/fuelup/pull/591
https://github.com/orgs/FuelSupply/repositories

### Fuel projects you have worked on

https://github.com/orgs/FuelSupply/repositories

Some NFTs staff

### Activity on the Fuel forum

https://forum.fuel.network/u/yusongwang/summary

### Links to your social media profiles

https://twitter.com/Yusong_Wang

### Current Champions member

Yes, I'm a Pro and applying to level up to Veteran

### Fuel Ambassador Program

No, I'm not a Fuel Ambassador

### Code of Conduct Agreement

- [X] I agree to follow the Code of Conduct

**Comment by hummusonrails** [comment]
Hi @YusongWang,

Your request to move to **Veteran** status has been approved! Welcome to the next level in the Champions program! 🎉 

Ben
